



name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: 
     - 'master'

jobs:
  buildApp:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    - uses: actions/checkout@master
    - run: go build ./cmd/*
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "./main"
        REMOTE_HOST: 188.225.77.132
        REMOTE_USER: "root"
        TARGET: "some"